### ISSUE TITLE
Usage of Admin API

### ISSUE THREAD

**Issue by BaseCrusher** [NikiforovAll/keycloak-authorization-services-dotnet#27]
Even though there is currently a client for Admin API there is no option to obtain the JWT token for the Admin, which is required for the majority of API's. And when obtaining it manually there is no way to set it for the client.

**Comment by JonathonCwik** [comment]
@NikiforovAll Yeah I'm a bit perplexed by this too. I tried setting it up how you have it in the simple sample where you technically use the same credentials for the Admin API and AuthN/AuthZ and I'm getting a 403 Forbidden trying to create a user.

**Comment by NikiforovAll** [comment]
We should use a separate account in order to integrate with admin API, it should have corresponding roles/permissions. I'm going to create an example for you guys. Also, feel free to contribute if you figure this out :)

**Comment by JonathonCwik** [comment]
I looked through the master clients for a client with a client id/secret and couldn't find anything and as far as I'm aware, the proper way to create a user is through the master realm 🤷

**Comment by victor-borges** [comment]
> I'm getting a 403 Forbidden trying to create a user.

The way de Admin API is setup right now is that it uses the same client ID and client secret from the configuration, in the Keycloak instance you need to make sure the client has the `manage-users` role applied, I think this is worth documenting.

**Comment by NikiforovAll** [comment]
an example with README.md file with instructions might do the trick. I just don't have time for it atm

**Comment by NikiforovAll** [comment]
friends, PRs are welcome as usual

**Comment by marcbouissa** [comment]
hello,can you please provide a small exemple on how to use it ?
I keep getting 401 unauthorized even when i provide a client secret

**Comment by timofdev** [comment]
Colleagues, confirm or correct me - a new user can only be created through the admin rest api using the Bearer authorization header with an administrator access token?

**Comment by victor-borges** [comment]
> Colleagues, confirm or correct me - a new user can only be created through the admin rest api using the Bearer authorization header with an administrator access token?

I don't think there's a concept of administrator access token, to be able to create a user you need to be authenticated with something that has the `manage-users` client role applied (for each realm that you want to manage), be it a user or a client. In the case of this library, it uses the client ID and client secret specified in your configuration, so that client needs the role applied.

**Comment by timofdev** [comment]
> > Colleagues, confirm or correct me - a new user can only be created through the admin rest api using the Bearer authorization header with an administrator access token?
> 
> I don't think there's a concept of administrator access token, to be able to create a user you need to be authenticated with something that has the `manage-users` client role applied (for each realm that you want to manage), be it a user or a client. In the case of this library, it uses the client ID and client secret specified in your configuration, so that client needs the role applied.

Victor, I'm currently developing a service for interacting with Keycloak. I am using the latest version of Keycloak - 21.1.1, but it seems like your library uses a different version, as the endpoints contain 'auth/', which is not present in the current version. I only interact with Keycloak through the Admin REST API, and the only available option for adding a new user is by using the POST `{base url}/admin/realms/{realm}/users` endpoint. To do this, we need to use Bearer authorization and add an administrator access token to the request header, otherwise the request will be unauthorized and a 401 status code will be returned. In the request body, we include a JSON object with information about the user that we want to create.

For example:
`curl -X POST \
  'http://{keycloak-url}/admin/realms/{realm}/users' \
  -H 'Authorization: Bearer {access-token}' \
  -H 'Content-Type: application/json' \
  -d '{
        "username": "new_user",
        "email": "new_user@example.com",
        "enabled": true,
        "credentials": [
            {
                "type": "password",
                "value": "password",
                "temporary": false
            }
        ]
    }'
`

I will also say that there are no `manage-users` in the current version.

Therefore, could you please explain how to create a new user using client_id and client_secret with the REST API? If possible, could you also provide an example using a curl request? I couldn't figure out the code in your library, that's why I'm asking.

**Comment by victor-borges** [comment]
@timofdev the endpoints themselves do not add the `/auth` prefix, that is something you can add to your keycloak URL in the config (same as the examples in the README.md) or you can just leave it out like this:

```json
{
  "Keycloak": {
    "Realm": "realm",
    "AuthServerUrl": "http://localhost:8080/",
    "SslRequired": "external",
    "VerifyTokenAudience": true,
    "Resource": "client-id",
    "Credentials": {
      "Secret": "client-secret"
    }
  }
}
```

Configuration remains the same, add this to `Program.cs`:

```csharp
builder.Services.AddKeycloakAuthentication(configuration);
```

For the `manage-users` role, it's actually a Service account role, on the Clients page, select the client, in the Service accounts roles click on Assign role, filter by clients, search for `manage-users` and assign, 

![image](https://user-images.githubusercontent.com/46226318/235548402-13ceedf6-65e6-4efe-9dad-8b3dbd8eb8f9.png)
![image](https://user-images.githubusercontent.com/46226318/235548488-6b3f0c4f-b7ad-43be-a6c3-5d598280bd3a.png)

Then, to create a user, you can inject either `IKeycloakUserClient` or `IKeycloakClient` and pass a user object to the create method, example below is the code I'm using right now with Keycloak 20 (realm configured to use email as username, so I don't include it):

```csharp
public async Task<ErrorOr<string>> CreateUserAsync(string email, string password, string? fullName)
{
    var (firstName, lastName) = fullName?.SplitFullName() ?? (null, null);

    var user = new User
    {
        Email = email,
        FirstName = firstName,
        LastName = lastName,
        Enabled = true,
        EmailVerified = false,
        Credentials = new[] {new Credential {Type = "password", Value = password, Temporary = false}}
    };

    using var response = await _keycloakUserClient.CreateUser(_applicationContext.Settings.Keycloak.Realm, user);

    if (!response.IsSuccessStatusCode)
    {
        _logger.LogError(
            "Error while creating Keycloak user: {@User}; Response: {@UserCreationResponse}, Response Content: {@UserCreationResponseContent}",
            user, response, await response.Content.ReadAsStringAsync());

        return Errors.Authentication.UserCreationFailed;
    }

    return response.Headers.Location?.AbsolutePath.Split('/').LastOrDefault() ?? string.Empty;
}
```

**Comment by timofdev** [comment]
@victor-borges Victor, thank you very much! I found it, figured it out, and it helped! Now I can obtain an access token using client_id and client_secret, include it in the authorization header with the bearer scheme, and create a new user. The main thing, as Victor correctly mentioned earlier, is to add the 'manage-users' role to your client for the service account
