### ISSUE TITLE
No Redirect to Keycloak Login Page

### ISSUE THREAD

**Issue by nefarius** [NikiforovAll/keycloak-authorization-services-dotnet#9]
Hello!

First of all; great library! I've tinkered with it and the provided samples but I guess I'm misunderstanding something; instead of getting redirected to the Keycloak Login page when I hit a protected endpoint I get a 401. Is this by design or am I missing the obvious?

Thanks for reading! 👋

**Comment by NikiforovAll** [comment]
Hi,

The library provides a convenient setup for a Web API scenario by default,  the simplest way is to look at the source code and adjust it according to the web scenario.

Contributions are welcome so that we can add something like `AddKeycloakAuthenticationWeb()`.
 
 By Web App, I mean something like this: <https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/1-WebApp-OIDC>
 
 You might find it helpful - <https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers> has a Keycloak provider.

**Comment by NikiforovAll** [comment]
Alternatively, you can use try to use `JwtBearerOptions` overload -  <https://github.com/NikiforovAll/keycloak-authorization-services-dotnet/blob/main/src/Keycloak.AuthServices.Authentication/ServiceCollectionExtensions.cs#L23>

Also, you can always override options, but I haven't tested this scenario.
```chsarp
services.AddKeycloakAuthentication(configuration, o =>
{
    o.CallbackPath = ""
    o.RedirectUri = ""
});
```

**Comment by nefarius** [comment]
Thanks for the swift response, you pointed me in the right direction, I got it to work swiftly using [`Microsoft.AspNetCore.Authentication.OpenIdConnect`](https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.OpenIdConnect/) with the following configuration:

```csharp
    builder.Services.AddAuthentication(options =>
        {
            options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
        })
        .AddCookie()
        .AddOpenIdConnect(o =>
            {
                o.RequireHttpsMetadata = false;
                o.ClientId = "myclient";
                o.Authority = "http://localhost:8080/realms/DEMOREALM";
                o.AuthenticationMethod = OpenIdConnectRedirectBehavior.RedirectGet;
                o.ResponseType = OpenIdConnectResponseType.Code;
                o.ResponseMode = OpenIdConnectResponseMode.Query;
                o.GetClaimsFromUserInfoEndpoint = true;
                o.CorrelationCookie = new CookieBuilder();
            }
        );

```

Cheers!
